### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPy#461] opened 2023-05-16 13:22 UTC
Hi @ntustison , 

Lots of test failures on the most recent PR. 

https://github.com/ANTsX/ANTsPy/actions/runs/4969163765/jobs/8892176590

Errors about transform factories - do you think these could be related to the recent troubles with ANTsR? But I don't get why this is suddenly a thing. The runners should be the same since the switch to Ubuntu 22.04 in October 2022 (https://github.com/actions/runner-images/issues/6399). The ANTs version has not changed since #442. But there are some settings in the runners that might change. I'll see what I can do to help lock those down.

Did your recent PR build successfully on your machine? Would you mind sharing the details of what system, compiler you used?

**Comment by ntustison** [comment] 2023-05-16 13:35
No, I'm pretty sure this stems from [this commit](https://github.com/ANTsX/ANTsPy/pull/459) from @richardbeare which expands template building to include the linear averaging step.  The problem is that the original code from Gang uses the MatrixOffsetTransformBase class which, I learned from Hans a long time ago, was never meant to actually be used which is why it's not registered with the other transform factories.  So it's unrelated but it still needs to get fixed.  I'll try to look at it later.

**Comment by ntustison** [comment] 2023-05-16 13:48
I think it's [here](https://github.com/ANTsX/ANTsPy/blob/master/ants/lib/register_transforms.h#L18-L19).  Let me see if that fixes it.

**Comment by ntustison** [comment] 2023-05-16 13:50
https://github.com/ANTsX/ANTsPy/pull/462

**Comment by cookpa** [comment] 2023-05-16 13:52
Thanks - hopefully that does it

**Comment by ntustison** [comment] 2023-05-16 15:36
Closing as it looks like the PR fixed the issue.  Thanks @cookpa .

**Closed by ntustison** 2023-05-16 15:36 UTC

**Comment by richardbeare** [comment] 2023-05-17 00:02
Sorry! :facepalm:

**Comment by cookpa** [comment] 2023-05-17 00:14
> Sorry! :facepalm:

It's all good - thanks for the new functionality
