### ISSUE TITLE
to_nibabel and from_nibabel don't cancel out

### ISSUE THREAD

**Issue by dangom** [ANTsX/ANTsPy#64] opened 2019-07-06 00:24 UTC
**Describe the bug**
I believe this may be related to #52. I've just built AntsPy from master, though, so the fix for #52 doesn't solve the issue.
For an ANTsImage (RSA), converting to and from nibabel changes their orientation (or at least their display). Also values for spacing and direction change.

**To Reproduce**

```python
import ants
data = ants.image_read("some_nifti_rsa.nii")
ants.plot_ortho(data, flat=True)
ants.plot_ortho(ants.from_nibabel(ants.to_nibabel(data)), flat=True)
```

**Expected behavior**
The to_nibabel and from_nibabel conversions cancel each other out?

**Screenshots**

<img width="554" alt="Screen Shot 2019-07-05 at 20 16 18" src="https://user-images.githubusercontent.com/7881842/60749011-73922300-9f83-11e9-9f57-949beb199424.png">
<img width="619" alt="Screen Shot 2019-07-05 at 20 19 42" src="https://user-images.githubusercontent.com/7881842/60749036-c966cb00-9f83-11e9-851c-6e270f91d863.png">

**Desktop (please complete the following information):**
 - OS: mac high sierra
 - ANTsPy: master
 - nibabel: 2.3.3

**Comment by stnava** [comment] 2019-07-06 00:38
I've tested this in the past and it "works for me"

this probably tests the same thing:

https://github.com/ANTsX/ANTsPy/blob/5ed4d119242eeb6a61c4663389be83c9bac71ab5/tests/test_core_ants_image_io.py#L270-L277

is there something different about these images?   if you look at the code, I don't think there is any way that spacing could change as you describe .......  would need a reproducible example to debug.

**Comment by stnava** [comment] 2019-07-06 00:39
also ITK coords are LPS.

**Comment by dangom** [comment] 2019-07-06 00:55
Yes, `get_ants_data('mni')` doesn't showcase the issue. I tried that too as I thought that'd be a more reproducible example.
Try with the following data (zipped because github)
[clone.nii.zip](https://github.com/ANTsX/ANTsPy/files/3364261/clone.nii.zip)

```python
import ants
data = ants.image_read("~/Downloads/clone.nii")
ants.plot_ortho(data, flat=True)
ants.plot_ortho(ants.from_nibabel(ants.to_nibabel(data)), flat=True)
```

**Comment by stnava** [comment] 2019-07-06 21:30
probably resolved with https://github.com/ANTsX/ANTsPy/commit/30b003882f18e15fc55c3818bee4f6981a9aad2d

please reopen if not

**Closed by stnava** 2019-07-06 21:30 UTC
