### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by SZUHvern** [ANTsX/ANTsPy#154] opened 2020-04-16 04:25 UTC
**Describe the bug**
I am trying to register images by using ANTsPy. However, when i try to debug both
 ' fixed_img.plot(overlay=moving_img, title='Before Registration')' or ''mytx = ants.registration(fixed=fixed_img, moving=moving_img, type_of_transform='SyN')'.  The same problem occured:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/siat/pycharm-2020.1/plugins/python/helpers/pydev/pydevd.py", line 1775, in stoptrace
    debugger.exiting()
  File "/home/siat/pycharm-2020.1/plugins/python/helpers/pydev/pydevd.py", line 1461, in exiting
    sys.stdout.flush()
ValueError: I/O operation on closed file.

I guess this is because  my pyqt version does not match? i have tried reinstalling pyqt, but it still doesn't work. 
My pyqt version is: 5.9.2 and pytest is 5.4.1.

By the way, 'ants.from_numpy()' can work, which i can got:
ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (224, 224)
	 Spacing    : (1.0, 1.0)
	 Origin     : (0.0, 0.0)
	 Direction  : [1. 0. 0. 1.]

**Comment by stnava** [comment] 2020-04-16 14:28
please read https://stackoverflow.com/help/minimal-reproducible-example

**Comment by stnava** [comment] 2020-04-20 20:59
closing because suspected not a reproducible issue.

**Closed by stnava** 2020-04-20 20:59 UTC
